import type{Finding,Issue,JevResponse,LineCandidate,ReviewPack}from'./types.ts';
export const MODEL='jev-1.13.0';
export function linesFromSelection(text:string,baseLine:number,firstCharacter=0):LineCandidate[]{const lines=text.replaceAll('\r\n','\n').split('\n'),result:LineCandidate[]=[];for(let i=0;i<lines.length&&result.length<255;i++){const raw=lines[i],leading=raw.length-raw.trimStart().length,content=raw.trim();if(!content)continue;const start=(i===0?firstCharacter:0)+leading;result.push({id:`line_${result.length+1}`,line:baseLine+i,startCharacter:start,endCharacter:start+content.length,text:content})}if(!result.length)throw new Error('Select at least one non-empty line');return result}
export function validatePack(pack:ReviewPack){if(!pack?.id||!pack.issues?.length)throw new TypeError('pack requires id and issues');const ids=new Set<string>();for(const issue of pack.issues){if(!issue.id||ids.has(issue.id)||!issue.label||!issue.instructions)throw new TypeError('issues require unique ids, labels and instructions');if(issue.markAbove<0||issue.markAbove>1)throw new TypeError(`${issue.id}: markAbove must be in [0,1]`);ids.add(issue.id)}return pack}
export function detectionRequest(lines:LineCandidate[],pack:ReviewPack){validatePack(pack);return{model:MODEL,state:{selectedLines:lines.map(({id,text})=>({id,text}))},questions:Object.fromEntries(pack.issues.map(issue=>[issue.id,{type:'noul',instructions:issue.instructions}]))}}
export function issuesToLocate(response:JevResponse,pack:ReviewPack):Issue[]{return pack.issues.filter(issue=>{const answer=response.answers[issue.id];return answer?.type==='noul'&&answer.noul>=issue.markAbove})}
export function locationRequest(lines:LineCandidate[],issues:Issue[]){const criteria=Object.fromEntries(lines.map(line=>[line.id,{text:line.text}]));return{model:MODEL,state:{selectedLines:lines.map(({id,text})=>({id,text}))},questions:Object.fromEntries(issues.map(issue=>[issue.id,{type:'choice',instructions:`Which exact selected line most strongly demonstrates this issue? ${issue.instructions}`,criteria}]))}}
export function validateResponse(response:JevResponse,questions:Record<string,{type:string;criteria?:Record<string,unknown>}>){if(response?.model!==MODEL||!response.answers||!Number.isInteger(response.usage?.input_tokens))throw new TypeError('Invalid Jev response envelope');for(const[id,question]of Object.entries(questions)){const answer=response.answers[id];if(!answer||answer.type!==question.type)throw new TypeError(`Missing or mismatched answer: ${id}`);if(answer.type==='noul'&&(!Number.isFinite(answer.noul)||answer.noul<0||answer.noul>1))throw new TypeError(`Invalid noul: ${id}`);if(answer.type==='choice'&&!(answer.choice in (question.criteria??{})))throw new TypeError(`Invalid choice: ${id}`)}return response}
export function findings(lines:LineCandidate[],issues:Issue[],response:JevResponse):Finding[]{const byId=new Map(lines.map(line=>[line.id,line]));return issues.flatMap(issue=>{const answer=response.answers[issue.id];const candidate=answer?.type==='choice'?byId.get(answer.choice):undefined;return candidate?[{issue,candidate}]:[]})}

